name: Package vbsp
on:
  - push


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
       
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v12

      - name: Verify emsdk
        run: emcc -v

      - name: Build on windows
        if: runner.os == 'Windows'
        run: ./build.bat
      
      - name: Build on linux
        if: runner.os == 'Linux'
        run: chmod +x ./build.sh && bash ./build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}
          path: ${{ github.workspace }}